# Generated by Django 4.2 on 2025-05-13 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('clientes', 'Reporte de Clientes'), ('pagos', 'Reporte de Pagos'), ('facturas', 'Reporte de Facturación'), ('contratos', 'Reporte de Contratos'), ('personalizado', 'Reporte Personalizado')], max_length=50)),
                ('parametros', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Guardado',
                'verbose_name_plural': 'Reportes Guardados',
                'db_table': 'reportes_guardados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('widgets_activos', models.JSONField(default=dict, verbose_name='Widgets Activos')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Dashboard',
                'verbose_name_plural': 'Configuraciones de Dashboard',
                'db_table': 'dashboard_config',
            },
        ),
    ]
