# Generated by Django 4.2 on 2025-05-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula/RUC')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('sector', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('velocidad_mbps', models.IntegerField(verbose_name='Velocidad (Mbps)')),
                ('tarifa_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Mensual')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_activo', models.BooleanField(default=True, verbose_name='¿Plan Activo?')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'planes',
                'ordering': ['tarifa_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('direccion_instalacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de Instalación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
