# Generated by Django 4.2 on 2025-05-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('deposito', 'Depósito Bancario'), ('otro', 'Otro')], max_length=50, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='completado', max_length=30)),
                ('mes_servicio', models.CharField(max_length=20, verbose_name='Mes de Servicio')),
                ('anio_servicio', models.IntegerField(verbose_name='Año de Servicio')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('factura', 'Factura Emitida'), ('pago', 'Pago Recibido'), ('recordatorio', 'Recordatorio de Pago'), ('suspension', 'Aviso de Suspensión'), ('promocion', 'Promoción'), ('otro', 'Otro')], max_length=50)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(choices=[('email', 'Correo Electrónico'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('app', 'Notificación App')], max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('estado_envio', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='enviado', max_length=20, verbose_name='Estado de Envío')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de Acceso SRI')),
                ('estado_sri', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50, verbose_name='Estado SRI')),
                ('ruta_pdf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta PDF')),
                ('ruta_xml', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta XML')),
                ('id_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
