# Generated by Django 4.2 on 2025-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
