# Stub file for rest_framework
from typing import Any

class views:
    class APIView: ...

class response:
    class Response: ...

class permissions:
    class IsAuthenticated: ...
    class AllowAny: ...
    class IsAdminUser: ...
    class IsAuthenticatedOrReadOnly: ...

class serializers:
    class Serializer: ...
    class ModelSerializer: ...

class viewsets:
    class ViewSet: ...
    class ModelViewSet: ...

class routers:
    class DefaultRouter: ...