# Stub file for rest_framework_simplejwt
from typing import Any

class views:
    class TokenObtainPairView: ...
    class TokenRefreshView: ...

class serializers:
    class TokenObtainPairSerializer: ...
    class TokenRefreshSerializer: ...

class authentication:
    class JWTAuthentication: ...
    